package {
	//Generated by rake
	
	import flash.display.Sprite;
	import flash.text.Font;

	dynamic public class Helvetica extends Sprite
	{
		
			[Embed(source='helvetica normal.ttf', fontName='helvetica', fontStyle='normal', fontWeight='normal', mimeType='application/x-font')]
			private var f0:Class;
		
		
		public var fonts:Array = [f0];
		
		public function Helvetica()
		{
			for(var i:int = 0; i < fonts.length; i++)
			{
				Font.registerFont(fonts[i]);
			}
		}
	}
}