package {
	//Generated by rake
	
	import flash.display.Sprite;
	import flash.text.Font;

	dynamic public class Myriad extends Sprite
	{
		
			[Embed(source='myriad normal.ttf', fontName='myriad', fontStyle='normal', fontWeight='normal', mimeType='application/x-font')]
			private var f0:Class;
		
			[Embed(source='myriad bold.ttf', fontName='myriad', fontStyle='normal', fontWeight='bold', mimeType='application/x-font')]
			private var f1:Class;
		
			[Embed(source='myriad italic.ttf', fontName='myriad', fontStyle='italic', fontWeight='normal', mimeType='application/x-font')]
			private var f2:Class;
		
		
		public var fonts:Array = [f0, f1, f2];
		
		public function Myriad()
		{
			for(var i:int = 0; i < fonts.length; i++)
			{
				Font.registerFont(fonts[i]);
			}
		}
	}
}