package {
	//Generated by rake
	
	import flash.display.Sprite;
	import flash.text.Font;

	dynamic public class Tradegothic extends Sprite
	{
		
			[Embed(source='tradegothic normal.ttf', fontName='tradegothic', fontStyle='normal', fontWeight='normal', mimeType='application/x-font')]
			private var f0:Class;
		
			[Embed(source='tradegothic bold.ttf', fontName='tradegothic', fontStyle='normal', fontWeight='bold', mimeType='application/x-font')]
			private var f1:Class;
		
		
		public var fonts:Array = [f0, f1];
		
		public function Tradegothic()
		{
			for(var i:int = 0; i < fonts.length; i++)
			{
				Font.registerFont(fonts[i]);
			}
		}
	}
}