package {
	//Generated by rake
	
	import flash.display.Sprite;
	import flash.text.Font;

	dynamic public class Utopia extends Sprite
	{
		
			[Embed(source='utopia normal.ttf', fontName='utopia', fontStyle='normal', fontWeight='normal', mimeType='application/x-font')]
			private var f0:Class;
		
			[Embed(source='utopia bold.ttf', fontName='utopia', fontStyle='normal', fontWeight='bold', mimeType='application/x-font')]
			private var f1:Class;
		
			[Embed(source='utopia italic.ttf', fontName='utopia', fontStyle='italic', fontWeight='normal', mimeType='application/x-font')]
			private var f2:Class;
		
			[Embed(source='utopia bolditalic.ttf', fontName='utopia', fontStyle='italic', fontWeight='bold', mimeType='application/x-font')]
			private var f3:Class;
		
		
		public var fonts:Array = [f0, f1, f2, f3];
		
		public function Utopia()
		{
			for(var i:int = 0; i < fonts.length; i++)
			{
				Font.registerFont(fonts[i]);
			}
		}
	}
}